### PR TITLE
Mnemocards Enhancement Proposal

### PR DESCRIPTION
**Pull request by guiferviz**
Writing the first Mnemocards Enhancement Proposal (MEP01). These documents are nothing more than Mnemocard RFCs or an equivalent of Python PEPs for example.

In MEP01 we describe what we are expecting in version 1.0.

[Attaching PDF](https://github.com/guiferviz/mnemocards/files/7612174/mep01.pdf) of the `adoc` file generated with Asciidoctor. It includes diagrams generated with MermaidJS.

Any feedback is more than welcome.

### CODE REVIEW

**Comment by guiferviz** [comment]
@Otter-man hey! In this PR there is a description of what I think we should have on Mnemocards v1.0. At the moment there are not too many low level details, but if you want to contribute some ideas you are more than welcome!

**Comment by Otter-man** [comment]
@guiferviz good day to you.
Great job on MEP01.

The new structure you proposed looks very sound and it does solve problems the current one has.

I don't have anything to add right now but will look into the current code and configs see if I have anything to add for future MEPs

Just to mention as to not forget some QOL improvements that would be nice to implement while refactoring code:
- ability to add any media file supported by anki, not only images, for `markdown` type.
- add auto-generation of UUID for card ID field based on seed. 
  `markdown` type has something like this - it uses hash of header as ID if none are given, but `vocabulary` and `expression` 
  doesn't check for ID and assign empty ID if none is given. I think future generator should check ID, if it's not UUID it assumes it is seed and uses it for generating UUID, and if none is given it generetes UUID with header as seed.

**Comment by guiferviz** [comment]
thanks @Otter-man that was the kind of input I needed!

I just closed #22 , I will take Windows into account!

Regarding the IDs, I know that the markdown type currently supports ID autogeneration, but I was never really convinced that it was a good idea. I set IDs on all my cards, with a Vim snippet I find it very easy to generate UUIDs. The problem I see is that if you fix a typo in the header (or in general any field used to autogenerate the ID), Anki will consider it as a new card because the autogenerated ID will be different. I don't think this is a very common problem, but it could happen. The 100% effective way to avoid this is to force the cards to have an explicit id. Can you think of a way to prevent or at least alert the user when something like this might be happening? What I want to avoid at all costs are _silent errors_ that the user does not notice until it is too late.

The best idea I had so far is to add a property in the configuration files, something like `"autogenerate_id": true`. This way Mnemocards will only autogenerate IDs if the user is are aware of the problems involved. By default that option would be false and we can print a warning if it is set to true just as a reminder.

**Comment by guiferviz** [comment]
Closing the PR, but feel free to continue the discussion here.

**Pull request merged**
