### PR TITLE
Using Poetry

### LINKED ISSUE #12: Use Poetry
Right now the installation process is a bit complicated due to the use of a custom version of Genanki. Using Poetry as package manager may make things easier, it would be nice to give it a try.

### PR DESCRIPTION
**Pull request by guiferviz**
Using **Poetry** to simplify the creation of a Python package and the management of its dependencies.
This PR will close #12 .

Also, as part of this PR, a customised version of Genanki for mnemocards has been published in Pypi:
* Pypi URL: https://pypi.org/project/genanki-mnemocards/
* Source code: https://github.com/guiferviz/genanki

This allows easy installation of mnemocards from pip: `pip install mnemocards`.

**TODO**:
- [x] Upload my own genanki version.
- [x] Create mnemocards pyproject.toml.
- [x] Update README.
- [x] Update Docker generation process.

### CODE REVIEW

**Comment by guiferviz** [comment]
@Otter-man FYI :)

After this my plan is to improve the tests and create some devops pipelines for testing PRs and auto-deploy the package to PyPi.

**Comment by Otter-man** [comment]
@guiferviz tested this PR and everything looks good, the error with `idna<3` doesn't reproduce on Poetry, after installation `idna==2.10` as required.

**Comment by Otter-man** [comment]
However, the requirement for `pop>=21` is a pain on my Ubuntu20.04, if one's using basic python3-venv you have to manually update pip in every virtual env you make (as far as I figured out for now).

Also, good job on updating your genanki to 0.11.0, I haven't seen you did it and used my own fork for the last half year.

**Comment by guiferviz** [comment]
Thanks for testing it!
With `pip<19` I get this error because of `orjson`.
image

Now that we are not using a repo URL in the dependencies (`genanki`) I think it's OK to say that pip should be `>=19`. When I create a venv the default version of pip is `9.0.1` so I still need to update pip.

I've created an empty venv and I've installed the wheel with `poetry build && pip install dist/mnemocards-0.1.4-py3-none-any.whl` (I think it should be equivalent to `pip install mnemocards`) and I'm getting `idna==3.3`. Looks like poetry takes into account the versions of the dependencies and pip doesn't... Anyways, I cannot reproduce your error, I can run the examples and also the tests with `idna==3.3`. Do you have some other packages installed in your venv apart from those required by mnemocards?

**Comment by Otter-man** [comment]
Previously when I first installed this PR I tried it on a clean venv, following instructions in readme.
However, when I checked `idna` the version was definitely `2.10`. (after `poetry build && pip install dist/mnemocards-0.1.4-py3-none-any.whl`)
But now when I try it on the new venv  I get `idna==3.3`

I think I downloaded this PR right before you committed https://github.com/guiferviz/mnemocards/pull/15/commits/24572512b20a876f81fc50226c171c85bc6d2a95
I see you changed the version to `requests==2.26.0` in this commit. They probably fixed the dependency issue there and it somehow solved to issue with `httpx` too (which is strange, since `httpx` version didn't change between the version on `master` branch and this one). And because of this Poetry installed `2.10` before and `3.3` now

So `idna` version issue can be considered solved in this PR by updating the version of `requests` and would not reproduce.

Also `pip` version can be `=>19`, `poetry build && pip install dist/mnemocards-0.1.4-py3-none-any.whl` works well on my default `pip==20.0.1` in venv.

**Comment by guiferviz** [comment]
Amazing, thanks for checking that. README already updated.
The docker image is now installing the wheel file generated by Poetry.
I will close this PR.

**Pull request merged**
